const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const values = new Map();
const context = vm.createContext({ localStorage: { getItem: key => values.get(key), setItem: (key, value) => values.set(key, value) } });
vm.runInContext(fs.readFileSync('renderer/personalization.js', 'utf8') + '\nthis.model = Personalization;', context);
const model = context.model;
const now = Date.now();
const article = { title: 'Neue Raumfahrt', desc: 'Forschung', cat: 'tech', sourceId: 'heise', sortTime: now };
const other = { ...article, title: 'Politik', cat: 'allgemein', sourceId: 'zeit' };
const profile = model.empty();
profile.interests = ['tech'];
assert.ok(model.score(article, profile, now) > model.score(other, profile, now));
profile.interests = [];
profile.keywords = ['raumfahrt'];
assert.ok(model.score(article, profile, now) > model.score(other, profile, now));
assert.match(model.reason(article, profile), /raumfahrt/);
profile.keywords = [];
profile.sources.heise = -2;
assert.ok(model.score(article, profile, now) < model.score(other, profile, now));
profile.sources.heise = 2;
assert.ok(model.score(article, profile, now) > model.score(other, profile, now));
assert.ok(model.score(article, profile, now) > model.score({ ...article, sortTime: now - 604800000 }, profile, now));
assert.equal(model.save(profile), true);
assert.equal(model.load().sources.heise, 2);
values.set('news.profile.v1', '{broken');
assert.equal(model.load().interests.length, 0);
values.set('news.profile.v1', JSON.stringify({ interests: ['invalid', 'tech', 'tech'], keywords: [42, 'Space'], sources: { heise: 99, zeit: 'invalid' } }));
const cleaned = model.load();
assert.equal(cleaned.interests.length, 1);
assert.equal(cleaned.keywords[0], 'space');
assert.equal(cleaned.sources.heise, 3);
assert.equal(cleaned.sources.zeit, undefined);
model.save(model.empty());
assert.equal(Object.keys(model.load().sources).length, 0);
context.localStorage.setItem = () => { throw new Error('quota'); };
assert.equal(model.save(profile), false);
console.log('Passed: topic and keyword ranking, feedback, recency, explanations, persistence, reset, malformed profile, validation, storage failure.');
